#!/usr/bin/env node
'use strict';

/**
 * Recreates this project's folder and file structure anywhere.
 *
 *   node scaffold.js [target-directory]
 *
 * Creates 52 directories and 228 files. Every file gets a
 * one-line header comment naming itself, so nothing reads as an accidentally empty
 * file — and the comment uses the right syntax for the format (`//` for JS, `--`
 * for SQL, `<!-- -->` for Markdown, and a valid `{ "_file": … }` object for JSON,
 * because a `//` line would make JSON unparseable).
 *
 * Safe to re-run: an existing file is never overwritten.
 *
 * This gives you the SHAPE, not the code. For a working copy of the project use
 * `git clone` — this is for starting a new project with the same layout.
 *
 * GENERATED by scripts/generate-scaffold.js on 2026-07-27 — do not hand-edit.
 */

const fs = require('fs');
const path = require('path');

const DIRS = [
  "backend",
  "e2e",
  "frontend",
  "scripts",
  "shared",
  "backend/certs",
  "backend/scripts",
  "backend/src",
  "backend/tests",
  "backend/uploads",
  "e2e/tests",
  "frontend/certs",
  "frontend/public",
  "frontend/src",
  "backend/scripts/prod-adoption",
  "backend/src/assets",
  "backend/src/config",
  "backend/src/constants",
  "backend/src/controllers",
  "backend/src/docs",
  "backend/src/middleware",
  "backend/src/migrations",
  "backend/src/models",
  "backend/src/routes",
  "backend/src/seeders",
  "backend/src/services",
  "backend/src/utils",
  "backend/src/validators",
  "backend/tests/helpers",
  "backend/tests/integration",
  "backend/tests/unit",
  "frontend/src/components",
  "frontend/src/context",
  "frontend/src/hooks",
  "frontend/src/lib",
  "frontend/src/pages",
  "backend/src/docs/paths",
  "backend/src/routes/v1",
  "backend/src/services/ai",
  "backend/src/services/storage",
  "frontend/src/components/__tests__",
  "frontend/src/components/blogs",
  "frontend/src/components/charts",
  "frontend/src/components/editor",
  "frontend/src/components/layout",
  "frontend/src/components/ui",
  "frontend/src/components/wizard",
  "frontend/src/lib/__tests__",
  "frontend/src/pages/__tests__",
  "frontend/src/components/editor/__tests__",
  "frontend/src/components/editor/settings",
  "frontend/src/components/wizard/__tests__"
];

const FILES = [
  ".gitattributes",
  ".gitignore",
  "API.md",
  "ARCHITECTURE.md",
  "backend/.dockerignore",
  "backend/.env.example",
  "backend/.sequelizerc",
  "backend/certs/.gitkeep",
  "backend/certs/README.md",
  "backend/certs/zscaler-root-ca.crt",
  "backend/docker-entrypoint.sh",
  "backend/Dockerfile",
  "backend/jest.config.js",
  "backend/package-lock.json",
  "backend/package.json",
  "backend/README.md",
  "backend/scripts/e2e-server.js",
  "backend/scripts/generate-block-fixtures.js",
  "backend/scripts/prod-adoption/001-add-ai-columns.sql",
  "backend/scripts/prod-adoption/002-rollback-ai-columns.sql",
  "backend/scripts/prod-adoption/backfill-slugs.js",
  "backend/src/app.js",
  "backend/src/assets/logo.png",
  "backend/src/config/database.js",
  "backend/src/config/index.js",
  "backend/src/config/sequelize-cli.js",
  "backend/src/constants/index.js",
  "backend/src/controllers/analytics.controller.js",
  "backend/src/controllers/auth.controller.js",
  "backend/src/controllers/blogs.controller.js",
  "backend/src/controllers/brandVoice.controller.js",
  "backend/src/controllers/generation.controller.js",
  "backend/src/controllers/media.controller.js",
  "backend/src/controllers/serp.controller.js",
  "backend/src/docs/index.js",
  "backend/src/docs/paths/analytics.js",
  "backend/src/docs/paths/auth.js",
  "backend/src/docs/paths/blogs.js",
  "backend/src/docs/paths/brandVoice.js",
  "backend/src/docs/paths/generation.js",
  "backend/src/docs/paths/media.js",
  "backend/src/docs/paths/serp.js",
  "backend/src/middleware/auth.js",
  "backend/src/middleware/errorHandler.js",
  "backend/src/middleware/rateLimit.js",
  "backend/src/middleware/upload.js",
  "backend/src/middleware/validate.js",
  "backend/src/migrations/20260727120000-create-users-table.js",
  "backend/src/migrations/20260727120100-create-blogs-table.js",
  "backend/src/models/blog.js",
  "backend/src/models/index.js",
  "backend/src/models/user.js",
  "backend/src/routes/v1/analytics.routes.js",
  "backend/src/routes/v1/auth.routes.js",
  "backend/src/routes/v1/blogs.routes.js",
  "backend/src/routes/v1/brandVoice.routes.js",
  "backend/src/routes/v1/generate.routes.js",
  "backend/src/routes/v1/index.js",
  "backend/src/routes/v1/media.routes.js",
  "backend/src/routes/v1/serp.routes.js",
  "backend/src/seeders/20260727130000-seed-users.js",
  "backend/src/seeders/20260727130100-seed-blogs.js",
  "backend/src/server.js",
  "backend/src/services/ai/AnthropicProvider.js",
  "backend/src/services/ai/BaseProvider.js",
  "backend/src/services/ai/index.js",
  "backend/src/services/ai/MockProvider.js",
  "backend/src/services/ai/OpenAIProvider.js",
  "backend/src/services/ai/prompts.js",
  "backend/src/services/analyticsService.js",
  "backend/src/services/blocksToHtml.js",
  "backend/src/services/blogService.js",
  "backend/src/services/brandVoice.js",
  "backend/src/services/generation.js",
  "backend/src/services/imageGeneration.js",
  "backend/src/services/logoComposite.js",
  "backend/src/services/sanitize.js",
  "backend/src/services/seoScore.js",
  "backend/src/services/serp.js",
  "backend/src/services/slug.js",
  "backend/src/services/storage/index.js",
  "backend/src/services/storage/LocalDriver.js",
  "backend/src/services/storage/S3Driver.js",
  "backend/src/services/storage/StorageDriver.js",
  "backend/src/services/tokens.js",
  "backend/src/utils/ApiError.js",
  "backend/src/utils/asyncHandler.js",
  "backend/src/utils/logger.js",
  "backend/src/validators/analytics.validators.js",
  "backend/src/validators/auth.validators.js",
  "backend/src/validators/blog.validators.js",
  "backend/src/validators/brandVoice.validators.js",
  "backend/src/validators/generation.validators.js",
  "backend/src/validators/media.validators.js",
  "backend/src/validators/serp.validators.js",
  "backend/tests/helpers/db.js",
  "backend/tests/helpers/factories.js",
  "backend/tests/integration/analytics.test.js",
  "backend/tests/integration/auth.test.js",
  "backend/tests/integration/blogs.test.js",
  "backend/tests/integration/brandVoice.test.js",
  "backend/tests/integration/generation.test.js",
  "backend/tests/integration/media.test.js",
  "backend/tests/integration/serp.test.js",
  "backend/tests/setup.js",
  "backend/tests/unit/aiProviders.test.js",
  "backend/tests/unit/authMiddleware.test.js",
  "backend/tests/unit/blocksToHtml.test.js",
  "backend/tests/unit/brandVoice-parser.test.js",
  "backend/tests/unit/config.test.js",
  "backend/tests/unit/generationConfig.test.js",
  "backend/tests/unit/logoComposite.test.js",
  "backend/tests/unit/migration-parity.test.js",
  "backend/tests/unit/seoScore.test.js",
  "backend/tests/unit/serp.test.js",
  "backend/tests/unit/storage.test.js",
  "backend/uploads/.gitkeep",
  "docker-compose.yml",
  "e2e/package-lock.json",
  "e2e/package.json",
  "e2e/playwright.config.js",
  "e2e/tests/full-flow.spec.js",
  "e2e/tests/responsive.spec.js",
  "frontend/.dockerignore",
  "frontend/certs/.gitkeep",
  "frontend/certs/README.md",
  "frontend/certs/zscaler-root-ca.crt",
  "frontend/Dockerfile",
  "frontend/nginx.conf",
  "frontend/package-lock.json",
  "frontend/package.json",
  "frontend/postcss.config.js",
  "frontend/public/index.html",
  "frontend/src/App.js",
  "frontend/src/components/__tests__/blockRenderer.parity.test.js",
  "frontend/src/components/BlockRenderer.js",
  "frontend/src/components/blogs/BlogFilters.js",
  "frontend/src/components/blogs/BlogGrid.js",
  "frontend/src/components/blogs/BlogPagination.js",
  "frontend/src/components/blogs/BlogRowActions.js",
  "frontend/src/components/blogs/BlogTable.js",
  "frontend/src/components/blogs/BlogThumbnail.js",
  "frontend/src/components/charts/ChartFrame.js",
  "frontend/src/components/charts/chartTheme.js",
  "frontend/src/components/charts/ChartTooltip.js",
  "frontend/src/components/charts/MonthlyAverageChart.js",
  "frontend/src/components/charts/PublishedOverTimeChart.js",
  "frontend/src/components/charts/RankedBarChart.js",
  "frontend/src/components/charts/ScoreDistributionChart.js",
  "frontend/src/components/charts/SerpRankChart.js",
  "frontend/src/components/charts/StatusDonutChart.js",
  "frontend/src/components/editor/__tests__/blockHistory.test.js",
  "frontend/src/components/editor/__tests__/blockSettings.test.js",
  "frontend/src/components/editor/AddBlockMenu.js",
  "frontend/src/components/editor/BlockBody.js",
  "frontend/src/components/editor/blockModel.js",
  "frontend/src/components/editor/BlockSettingsPanel.js",
  "frontend/src/components/editor/BlockToolbar.js",
  "frontend/src/components/editor/EditorCanvas.js",
  "frontend/src/components/editor/InlineEditable.js",
  "frontend/src/components/editor/PreviewPane.js",
  "frontend/src/components/editor/SaveStatus.js",
  "frontend/src/components/editor/settings/CtaSettings.js",
  "frontend/src/components/editor/settings/EmbedSettings.js",
  "frontend/src/components/editor/settings/FaqSettings.js",
  "frontend/src/components/editor/settings/HeadingSettings.js",
  "frontend/src/components/editor/settings/ImageSettings.js",
  "frontend/src/components/editor/settings/index.js",
  "frontend/src/components/editor/settings/KeyTakeawaySettings.js",
  "frontend/src/components/editor/settings/ListSettings.js",
  "frontend/src/components/editor/settings/ParagraphSettings.js",
  "frontend/src/components/editor/settings/QuoteSettings.js",
  "frontend/src/components/editor/settings/shared.js",
  "frontend/src/components/editor/settings/TableSettings.js",
  "frontend/src/components/editor/SortableBlock.js",
  "frontend/src/components/layout/AppLayout.js",
  "frontend/src/components/ui/Button.js",
  "frontend/src/components/ui/feedback.js",
  "frontend/src/components/ui/form.js",
  "frontend/src/components/ui/Spinner.js",
  "frontend/src/components/wizard/__tests__/titleScore.test.js",
  "frontend/src/components/wizard/InternalLinkPicker.js",
  "frontend/src/components/wizard/LogoPositionGrid.js",
  "frontend/src/components/wizard/OutlineBuilder.js",
  "frontend/src/components/wizard/SeoScoreBreakdown.js",
  "frontend/src/components/wizard/Step1Topic.js",
  "frontend/src/components/wizard/Step2BrandVoice.js",
  "frontend/src/components/wizard/Step3Content.js",
  "frontend/src/components/wizard/Step4Images.js",
  "frontend/src/components/wizard/Step5Publish.js",
  "frontend/src/components/wizard/Step6Generate.js",
  "frontend/src/components/wizard/StepIndicator.js",
  "frontend/src/components/wizard/steps.js",
  "frontend/src/components/wizard/titleScore.js",
  "frontend/src/components/wizard/TitleSuggestions.js",
  "frontend/src/components/wizard/WizardShell.js",
  "frontend/src/context/AuthContext.js",
  "frontend/src/hooks/useAutosave.js",
  "frontend/src/hooks/useBlockHistory.js",
  "frontend/src/hooks/useDebouncedValue.js",
  "frontend/src/hooks/useWizardDraft.js",
  "frontend/src/index.css",
  "frontend/src/index.js",
  "frontend/src/lib/__tests__/api.envelope.test.js",
  "frontend/src/lib/__tests__/constants.parity.test.js",
  "frontend/src/lib/api.js",
  "frontend/src/lib/constants.js",
  "frontend/src/lib/media.js",
  "frontend/src/lib/sanitizeInline.js",
  "frontend/src/pages/__tests__/blogList.test.js",
  "frontend/src/pages/__tests__/dashboard.test.js",
  "frontend/src/pages/__tests__/editor.test.js",
  "frontend/src/pages/__tests__/wizard.test.js",
  "frontend/src/pages/BlogListPage.js",
  "frontend/src/pages/BlogViewPage.js",
  "frontend/src/pages/DashboardPage.js",
  "frontend/src/pages/EditorPage.js",
  "frontend/src/pages/LoginPage.js",
  "frontend/src/pages/WizardPage.js",
  "frontend/src/setupTests.js",
  "frontend/tailwind.config.js",
  "README.md",
  "scripts/generate-scaffold.js",
  "scripts/scaffold.cmd",
  "scripts/scaffold.sh",
  "scripts/STRUCTURE.txt",
  "shared/block-fixtures.json",
  "TESTING.md"
];

/**
 * Header comment per format.
 *
 * Formats absent from this map get an empty file on purpose: images and
 * certificates are binary or structure-sensitive, and a text header would corrupt
 * them rather than annotate them.
 */
const COMMENT_BY_EXT = {
  '.js': (p) => `// ${p}\n`,
  '.jsx': (p) => `// ${p}\n`,
  '.mjs': (p) => `// ${p}\n`,
  '.cjs': (p) => `// ${p}\n`,
  '.ts': (p) => `// ${p}\n`,
  '.tsx': (p) => `// ${p}\n`,
  '.css': (p) => `/* ${p} */\n`,
  '.scss': (p) => `/* ${p} */\n`,
  '.md': (p) => `<!-- ${p} -->\n`,
  '.html': (p) => `<!-- ${p} -->\n`,
  '.sql': (p) => `-- ${p}\n`,
  '.sh': (p) => `#!/bin/sh\n# ${p}\n`,
  '.yml': (p) => `# ${p}\n`,
  '.yaml': (p) => `# ${p}\n`,
  '.cmd': (p) => `REM ${p}\r\n`,
  '.bat': (p) => `REM ${p}\r\n`,
  '.txt': (p) => `${p}\n`,
  // A comment would make JSON invalid, so the filename goes in a real key instead:
  // the file is non-empty AND still parses.
  '.json': (p) => `{\n  "_file": "${p}"\n}\n`,
};

/** Dotfiles and extensionless files, matched on basename. */
const COMMENT_BY_NAME = {
  '.gitignore': (p) => `# ${p}\n`,
  '.gitattributes': (p) => `# ${p}\n`,
  '.dockerignore': (p) => `# ${p}\n`,
  '.gitkeep': (p) => `# ${p}\n`,
  '.env.example': (p) => `# ${p}\n`,
  // .sequelizerc is JavaScript despite the extension.
  '.sequelizerc': (p) => `// ${p}\n`,
  Dockerfile: (p) => `# ${p}\n`,
};

/** Binary or format-sensitive: created empty rather than corrupted. */
const LEAVE_EMPTY = new Set(['.png', '.jpg', '.jpeg', '.webp', '.ico', '.crt', '.pem', '.der', '.woff', '.woff2']);

function headerFor(relativePath) {
  const base = path.basename(relativePath);
  if (COMMENT_BY_NAME[base]) return COMMENT_BY_NAME[base](relativePath);

  const ext = path.extname(base).toLowerCase();
  if (LEAVE_EMPTY.has(ext)) return '';
  if (COMMENT_BY_EXT[ext]) return COMMENT_BY_EXT[ext](relativePath);

  // Unknown extension: '#' is the most widely tolerated comment character.
  return `# ${relativePath}\n`;
}

const target = path.resolve(process.argv[2] || '.');

console.log(`Scaffolding into ${target}`);
fs.mkdirSync(target, { recursive: true });

let dirsMade = 0;
for (const dir of DIRS) {
  const full = path.join(target, dir);
  if (!fs.existsSync(full)) dirsMade += 1;
  fs.mkdirSync(full, { recursive: true });
}

let filesMade = 0;
let filesSkipped = 0;
let emptyFiles = 0;
for (const file of FILES) {
  const full = path.join(target, file);
  // Never clobber. Running this over a populated tree must be harmless.
  if (fs.existsSync(full)) {
    filesSkipped += 1;
    continue;
  }
  fs.mkdirSync(path.dirname(full), { recursive: true });
  const header = headerFor(file);
  if (header === '') emptyFiles += 1;
  fs.writeFileSync(full, header, 'utf8');
  filesMade += 1;
}

console.log(`  directories: ${DIRS.length} (${dirsMade} created)`);
console.log(`  files:       ${FILES.length} (${filesMade} created, ${filesSkipped} already existed)`);
if (emptyFiles > 0) {
  console.log(`  ${emptyFiles} binary/certificate file(s) left empty — a text header would corrupt them.`);
}
console.log('');
console.log('Structure only — no code. Use `git clone` if you want a working copy.');