'use strict';

/**
 * YouTubeTranscriptProvider — real transcript retrieval for YouTube videos.
 *
 * ROOT CAUSE this replaces the old scrapeYoutubeCaptions() for: the legacy
 * approach (regex-parse `captionTracks` out of the watch page, GET the
 * `timedtext` `baseUrl` directly with plain axios) reliably DISCOVERS caption
 * tracks but the direct `timedtext` fetch now returns HTTP 200 with an EMPTY
 * body from this server. Investigation (see the audit conversation) proved
 * this is NOT a missing-signature/wrong-endpoint/header problem: even
 * YouTube's own unmodified page JS, run in a real (headless) Chromium via
 * Puppeteer, got the exact same rejection ("Precondition check failed") from
 * its OWN `youtubei/v1/get_transcript` call — until `navigator.webdriver`
 * and the `AutomationControlled` blink flag were hidden. That one change
 * flipped the SAME request to HTTP 200 with a real transcript. Root cause:
 * YouTube's anti-bot layer was detecting the headless-automation fingerprint,
 * not a missing token — so no BotGuard/PoT reimplementation was needed
 * (confirmed empirically: a jsdom-based PO-token generator was evaluated
 * first and abandoned after it crashed OOM trying to run YouTube's current,
 * more obfuscated BotGuard interpreter — see the final report for detail).
 *
 * Approach: launch one real (anti-detection-flagged) headless Chromium,
 * reused across calls (browser launch is the expensive part, ~1-2s; a new
 * tab per video is cheap). Navigate to the real watch page, let YOUTUBE'S
 * OWN JavaScript click through to "Show transcript" and make its own
 * `get_transcript` call — we only INTERCEPT that response, we never
 * hand-construct the request. This is deliberately more robust than
 * replicating YouTube's internal request-signing ourselves: as long as the
 * "Show transcript" UI exists, this keeps working even if YouTube changes
 * the request's internal shape again.
 *
 * Returns a normalized shape so the rest of the Knowledge Layer never needs
 * to know HOW a transcript was obtained:
 *   { videoId, status, transcript, segments, language, isAutoGenerated,
 *     sourceMethod: 'youtube_captions', confidence, retrievedAt, reason }
 * `status`: 'ok' | 'no_captions' | 'unavailable' | 'error'.
 */

const logger = require('../../../utils/logger');

const NAV_TIMEOUT_MS = 20000;
const TRANSCRIPT_RESPONSE_TIMEOUT_MS = 15000;
const MAX_ATTEMPTS = 3;
const RETRY_BACKOFF_MS = 1500;

const CHROME_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

// ---------------------------------------------------------------------------
// Browser lifecycle — one real Chromium reused across every call. Launching
// it is the slow/expensive part; a per-call new *page* is cheap. Relaunches
// itself lazily if the process dies/disconnects.
// ---------------------------------------------------------------------------
let browserPromise = null;

async function getBrowser() {
  if (browserPromise) {
    const existing = await browserPromise;
    if (existing.connected) return existing;
    browserPromise = null; // stale — relaunch below
  }
  const puppeteer = require('puppeteer');
  browserPromise = puppeteer
    .launch({
      headless: 'new',
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        // The actual fix (see module docstring): without this, YouTube's own
        // JS detects headless automation and its internal get_transcript
        // call gets rejected with "Precondition check failed" — even though
        // nothing about OUR request is wrong.
        '--disable-blink-features=AutomationControlled',
      ],
    })
    .catch((err) => {
      browserPromise = null;
      throw err;
    });
  return browserPromise;
}

/** Exported for graceful shutdown (server.js) — avoids a leaked Chromium process on restart/redeploy. */
async function closeBrowser() {
  if (!browserPromise) return;
  try {
    const browser = await browserPromise;
    await browser.close();
  } catch (err) {
    logger.warn('Error closing YouTube transcript browser', { message: err.message });
  } finally {
    browserPromise = null;
  }
}

// ---------------------------------------------------------------------------
// Transcript-panel scrape for one video.
// ---------------------------------------------------------------------------

/** Walks the get_transcript response body for transcriptSegmentRenderer nodes, in document order. */
function extractSegments(body) {
  const segments = [];
  const visit = (node) => {
    if (!node || typeof node !== 'object') return;
    if (Array.isArray(node)) {
      node.forEach(visit);
      return;
    }
    if (node.transcriptSegmentRenderer) {
      const seg = node.transcriptSegmentRenderer;
      const text = (seg.snippet?.runs || []).map((r) => r.text).join('');
      if (text.trim()) {
        segments.push({ text: text.trim(), startMs: Number(seg.startMs) || 0, endMs: Number(seg.endMs) || 0 });
      }
      return; // segment nodes don't nest further segments
    }
    for (const value of Object.values(node)) visit(value);
  };
  visit(body);
  return segments;
}

/** Finds which language menu entry is selected (YouTube's own default pick) and its raw title, e.g. "English (auto-generated)". */
function extractSelectedLanguageTitle(body) {
  let found = null;
  const visit = (node) => {
    if (found || !node || typeof node !== 'object') return;
    if (Array.isArray(node)) {
      node.forEach(visit);
      return;
    }
    if (node.sortFilterSubMenuRenderer?.subMenuItems) {
      const selected = node.sortFilterSubMenuRenderer.subMenuItems.find((item) => item.selected);
      if (selected) found = selected.title;
      return;
    }
    for (const value of Object.values(node)) visit(value);
  };
  visit(body);
  return found;
}

/** Finds every language menu entry (not just the selected one) — used to decide whether a language switch is needed/possible. */
function extractLanguageMenuItems(body) {
  let found = null;
  const visit = (node) => {
    if (found || !node || typeof node !== 'object') return;
    if (Array.isArray(node)) {
      node.forEach(visit);
      return;
    }
    if (node.sortFilterSubMenuRenderer?.subMenuItems) {
      found = node.sortFilterSubMenuRenderer.subMenuItems;
      return;
    }
    for (const value of Object.values(node)) visit(value);
  };
  visit(body);
  return found || [];
}

/**
 * @param {string} videoId
 * @param {object} [options]
 * @param {object} [options.browserOverride] Injected browser instance, for tests.
 * @param {string} [options.preferredLanguageCode] FIX 7 (language preference) — if given and
 *   available as a caption track, the transcript panel's language menu is switched to it
 *   instead of accepting whatever YouTube's own UI defaulted to. Best-effort: falls back
 *   to the default track if the switch can't be completed within the response timeout.
 * @param {boolean} [options.preferredAutoGenerated] Same mechanism, for choosing between a
 *   manual and an auto-generated track that share the same language code.
 * @returns {Promise<{videoId:string, status:'ok'|'no_captions'|'unavailable'|'error', transcript:string|null, segments:Array|null, language:string|null, isAutoGenerated:boolean|null, sourceMethod:'youtube_captions', confidence:number, retrievedAt:string, reason:string|null}>}
 */
async function fetchTranscriptOnce(videoId, { browserOverride, preferredLanguageCode, preferredAutoGenerated } = {}) {
  const browser = browserOverride || (await getBrowser());
  const page = await browser.newPage();
  const retrievedAt = new Date().toISOString();

  try {
    await page.evaluateOnNewDocument(() => {
      Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
    });
    await page.setUserAgent(CHROME_UA);
    await page.setViewport({ width: 1280, height: 800 });

    // Every matching response is captured (not just the first) — switching
    // the transcript panel's language fires a SECOND get_transcript call,
    // and we need to wait for that one specifically when a language switch
    // was requested and possible.
    const transcriptBodies = [];
    const responseListener = async (res) => {
      if (res.url().includes('/youtubei/v1/get_transcript')) {
        try {
          if (res.status() === 200) transcriptBodies.push(await res.json());
        } catch {
          /* non-JSON or already-consumed response — ignored, treated as no capture */
        }
      }
    };
    page.on('response', responseListener);

    await page.goto(`https://www.youtube.com/watch?v=${videoId}`, {
      waitUntil: 'networkidle2',
      timeout: NAV_TIMEOUT_MS,
    });

    const playerState = await page.evaluate(() => {
      const pr = window.ytInitialPlayerResponse;
      const tracks = pr?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
      return {
        playabilityStatus: pr?.playabilityStatus?.status || null,
        title: pr?.videoDetails?.title || null,
        author: pr?.videoDetails?.author || null,
        captionTracks: tracks.map((t) => ({
          languageCode: t.languageCode || null,
          isAutoGenerated: t.kind === 'asr',
          name: t.name?.simpleText || null,
        })),
      };
    });
    logger.info('YouTube transcript: page loaded', { videoId, playabilityStatus: playerState.playabilityStatus });

    if (playerState.playabilityStatus && playerState.playabilityStatus !== 'OK') {
      return {
        videoId,
        status: 'unavailable',
        transcript: null,
        segments: null,
        language: null,
        isAutoGenerated: null,
        sourceMethod: 'youtube_captions',
        confidence: 0,
        retrievedAt,
        reason: `Video not playable (playabilityStatus=${playerState.playabilityStatus}).`,
        title: playerState.title,
        author: playerState.author,
      };
    }

    if (playerState.captionTracks.length === 0) {
      logger.info('YouTube transcript: no caption tracks available', { videoId });
      return {
        videoId,
        status: 'no_captions',
        transcript: null,
        segments: null,
        language: null,
        isAutoGenerated: null,
        sourceMethod: 'youtube_captions',
        confidence: 0,
        retrievedAt,
        reason: 'This video has no caption tracks.',
        title: playerState.title,
        author: playerState.author,
      };
    }
    logger.info('YouTube transcript: caption tracks discovered', {
      videoId,
      tracks: playerState.captionTracks.map((t) => `${t.languageCode}${t.isAutoGenerated ? '(asr)' : ''}`),
    });

    // Expand the description (the "Show transcript" button lives under it) then click it.
    // The extra settle time is deliberate: clicking before YouTube's own JS has
    // finished attaching the panel's event handlers is a real, observed source
    // of intermittent "no response"/empty-segment failures (retried above).
    await page.evaluate(() => document.querySelector('tp-yt-paper-button#expand, #expand')?.click());
    await new Promise((resolve) => {
      setTimeout(resolve, 1500);
    });
    const clicked = await page.evaluate(() => {
      const buttons = Array.from(document.querySelectorAll('button, tp-yt-paper-button'));
      const btn = buttons.find((b) => /transcript/i.test(b.textContent || b.getAttribute('aria-label') || ''));
      if (btn) {
        btn.click();
        return true;
      }
      return false;
    });

    if (!clicked) {
      logger.warn('YouTube transcript: caption tracks exist but "Show transcript" control was not found', { videoId });
      return {
        videoId,
        status: 'error',
        transcript: null,
        segments: null,
        language: null,
        isAutoGenerated: null,
        sourceMethod: 'youtube_captions',
        confidence: 0,
        retrievedAt,
        reason: 'Caption tracks exist but the "Show transcript" control could not be found (page layout may have changed).',
        title: playerState.title,
        author: playerState.author,
      };
    }

    const waitForResponse = async (targetCount, timeoutMs) => {
      const start = Date.now();
      while (transcriptBodies.length < targetCount && Date.now() - start < timeoutMs) {
        // eslint-disable-next-line no-await-in-loop -- polling for one network event with a bounded timeout, not a hot loop.
        await new Promise((resolve) => {
          setTimeout(resolve, 200);
        });
      }
      return transcriptBodies.length >= targetCount;
    };

    if (!(await waitForResponse(1, TRANSCRIPT_RESPONSE_TIMEOUT_MS))) {
      page.off('response', responseListener);
      return {
        videoId,
        status: 'error',
        transcript: null,
        segments: null,
        language: null,
        isAutoGenerated: null,
        sourceMethod: 'youtube_captions',
        confidence: 0,
        retrievedAt,
        reason: 'Transcript panel opened but no get_transcript response arrived in time.',
        title: playerState.title,
        author: playerState.author,
      };
    }

    // FIX 7 — language preference: only attempt a switch if a specific
    // language (and/or auto-generated-vs-manual preference) was requested
    // and differs from what YouTube's own UI defaulted to. Best-effort — if
    // the menu/option can't be found or the second response never arrives,
    // we keep the default track rather than failing the whole retrieval.
    if (preferredLanguageCode || typeof preferredAutoGenerated === 'boolean') {
      const defaultTrackName = extractSelectedLanguageTitle(transcriptBodies[0]);
      const defaultTrack = playerState.captionTracks.find((t) => t.name === defaultTrackName);
      const defaultMatches =
        (!preferredLanguageCode || defaultTrack?.languageCode === preferredLanguageCode) &&
        (typeof preferredAutoGenerated !== 'boolean' || defaultTrack?.isAutoGenerated === preferredAutoGenerated);
      if (!defaultMatches) {
        const menuItems = extractLanguageMenuItems(transcriptBodies[0]);
        const wantedTrack = playerState.captionTracks.find(
          (t) =>
            (!preferredLanguageCode || t.languageCode === preferredLanguageCode) &&
            (typeof preferredAutoGenerated !== 'boolean' || t.isAutoGenerated === preferredAutoGenerated)
        );
        const wantedTitle = menuItems.find((item) => item.title === wantedTrack?.name)?.title;
        if (wantedTitle) {
          // eslint-disable-next-line no-await-in-loop -- single best-effort attempt, not a loop.
          const switched = await page.evaluate((title) => {
            const trigger = document.querySelector('yt-sort-filter-sub-menu-renderer')?.querySelector('button, tp-yt-paper-button, [role="button"]');
            if (!trigger) return false;
            trigger.click();
            return true;
          }, wantedTitle);
          if (switched) {
            await new Promise((resolve) => {
              setTimeout(resolve, 500);
            });
            await page.evaluate((title) => {
              const items = Array.from(document.querySelectorAll('tp-yt-paper-item, a.yt-simple-endpoint, [role="menuitem"]'));
              const match = items.find((i) => (i.textContent || '').trim() === title);
              if (match) match.click();
            }, wantedTitle);
            await waitForResponse(2, TRANSCRIPT_RESPONSE_TIMEOUT_MS);
          }
        } else {
          logger.info('YouTube transcript: preferred language not available, keeping default track', {
            videoId,
            preferredLanguageCode,
          });
        }
      }
    }
    page.off('response', responseListener);

    const transcriptBody = transcriptBodies[transcriptBodies.length - 1];
    const segments = extractSegments(transcriptBody);
    const transcript = segments.map((s) => s.text).join(' ').replace(/\s+/g, ' ').trim();
    const wordCount = transcript ? transcript.split(/\s+/).filter(Boolean).length : 0;

    // FIX 8 (validation, not a character-count proxy) — a real transcript has
    // multiple timed segments and actual words, not just a 200 status.
    if (segments.length === 0 || wordCount < 3) {
      return {
        videoId,
        status: 'error',
        transcript: null,
        segments: null,
        language: null,
        isAutoGenerated: null,
        sourceMethod: 'youtube_captions',
        confidence: 0,
        retrievedAt,
        reason: `Transcript response contained no meaningful text (segments=${segments.length}, words=${wordCount}).`,
        title: playerState.title,
        author: playerState.author,
      };
    }

    const selectedTitle = extractSelectedLanguageTitle(transcriptBody);
    const matchedTrack =
      playerState.captionTracks.find((t) => t.name === selectedTitle) ||
      playerState.captionTracks[0]; // best-effort fallback — never silently claim English if we can't confirm it

    logger.info('YouTube transcript: retrieved', {
      videoId,
      segments: segments.length,
      words: wordCount,
      language: matchedTrack.languageCode,
      isAutoGenerated: matchedTrack.isAutoGenerated,
    });

    return {
      videoId,
      status: 'ok',
      transcript,
      segments,
      language: matchedTrack.languageCode,
      isAutoGenerated: matchedTrack.isAutoGenerated,
      sourceMethod: 'youtube_captions',
      confidence: 1,
      retrievedAt,
      reason: null,
      title: playerState.title,
      author: playerState.author,
    };
  } finally {
    await page.close().catch(() => {});
  }
}

/**
 * @param {string} videoId
 * @param {object} [options]
 * @returns {Promise<object>} See fetchTranscriptOnce's return shape.
 */
async function fetchTranscript(videoId, options = {}) {
  let lastResult = null;
  let lastErr = null;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt += 1) {
    try {
      // eslint-disable-next-line no-await-in-loop -- bounded retry (MAX_ATTEMPTS), sequential by design.
      const result = await fetchTranscriptOnce(videoId, options);
      // A returned status:'error' (e.g. a transient panel-load timeout) is
      // just as retry-worthy as a thrown exception — a fresh page load often
      // clears it. 'no_captions'/'unavailable' are NOT retried: those are
      // real, stable facts about the video, not transient failures.
      if (result.status !== 'error') return result;
      lastResult = result;
      logger.warn('YouTube transcript attempt returned a transient error', { videoId, attempt, reason: result.reason });
    } catch (err) {
      lastErr = err;
      logger.warn('YouTube transcript attempt failed', { videoId, attempt, message: err.message });
    }
    if (attempt < MAX_ATTEMPTS) {
      // eslint-disable-next-line no-await-in-loop
      await new Promise((resolve) => {
        setTimeout(resolve, RETRY_BACKOFF_MS * attempt);
      });
    }
  }
  return (
    lastResult || {
      videoId,
      status: 'error',
      transcript: null,
      segments: null,
      language: null,
      isAutoGenerated: null,
      sourceMethod: 'youtube_captions',
      confidence: 0,
      retrievedAt: new Date().toISOString(),
      reason: lastErr?.message || 'Unknown transcript retrieval error.',
    }
  );
}

module.exports = { fetchTranscript, closeBrowser, getBrowser, MAX_ATTEMPTS };
